version: 0.0
os: linux
hooks:
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 1500
      runas: root
  ApplicationStart:
    - location: start_container.sh
      timeout: 50000
      runas: root
  ApplicationStop:
    - location: stop_container.sh
      timeout: 20000
      runas: root
