version: 0.0
os: linux
files:
  - source: /opt/codedeploy-agent/deployment-root/1b1ab9c0-744d-40f9-a2a2-a4ec9f761a2a/d-HO2PZ8MP3/deployment-archive/docker-compose.yml
    destination: /home/ec2-user/
    runas: root
hooks:
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 1500
      runas: root
  ApplicationStart:
    - location: scripts/start_container.sh
      timeout: 50000
      runas: root
  ApplicationStop:
    - location: scripts/stop_container.sh
      timeout: 20000
      runas: root
