version: 0.0
os: linux 
hooks:
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 1500
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start_container.sh
      timeout: 50000
      runas: ec2-user
  ApplicationStop:
    - location: scripts/stop_container.sh
      timeout: 20000
      runas: ec2-user
