version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html 
hooks:
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 1500
      runas: root
  ApplicationStart:
    - location: scripts/start_container.sh
      timeout: 50000
      runas: root
  ApplicationStop:
    - location: scripts/stop_container.sh
      timeout: 20000
      runas: root
