version: 0.0
os: linux
files:
  - source: /Docker compose
    destination: ~ /Jo_Agam_DevOps-project-super-app
hooks:
  AfterInstall:
    - location: scripts/install_dependencies&image.sh
      timeout: 1500
      runas: root
  ApplicationStart:
    - location: scripts/start_container.sh
      timeout: 50000
      runas: root
  ApplicationStop:
    - location: scripts/kill_container.sh
      timeout: 20000
      runas: root
