version: "3.9"
services:
  db:
    platform: Linux/amd64
    image: mysql:8.0.28
    container_name: jo_mysql
    command: mysqld --innodb_use_native_aio=0
    environment:
      MYSQL_DATABASE: super-app
      MYSQL_ROOT_PASSWORD: password
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent"]
      interval: 3s
      retries: 5
      start_period: 30s
    ports:
      - 3306:3306  
    volumes:
      - db-data:/var/lib/mysql
  node:
    build: ./node
    container_name: jo_node
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: super-app
    ports:
      - 3000:3000
    depends_on:
      db:
        condition: service_healthy
  php:
    build: ./php
    container_name: jo_php
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: super-app
    ports:
      - 80:80
    volumes:
      - ./php/:/var/www/html/  
    depends_on:
      db:
        condition: service_healthy
    stdin_open: true
    tty: true  

volumes:
  db-data:
  php:
